name: dtalent_app
description: DTALENT APP demo sin logos
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  pdf: ^3.10.7
  printing: ^5.13.4
  country_picker: ^2.0.20


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/dTalentLogo.png

